package actions

import (
	"fmt"
	"net/http"
	"twit_api/models"

	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop/v5"
	"github.com/gobuffalo/x/responder"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Detail)
// DB Table: Plural (details)
// Resource: Plural (Details)
// Path: Plural (/details)
// View Template Folder: Plural (/templates/details/)

// DetailsResource is the resource for the Detail model
type DetailsResource struct {
	buffalo.Resource
}

// List gets all Details. This function is mapped to the path
// GET /details
func (v DetailsResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	details := &models.Details{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all Details from the DB
	if err := q.All(details); err != nil {
		return err
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// Add the paginator to the context so it can be used in the template.
		c.Set("pagination", q.Paginator)

		c.Set("details", details)
		return c.Render(http.StatusOK, r.JSON(map[string]string{"message": "Welcome to details"}))
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(200, r.JSON(details))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(200, r.XML(details))
	}).Respond(c)
}

// Show gets the data for one Detail. This function is mapped to
// the path GET /details/{detail_id}
func (v DetailsResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Detail
	detail := &models.Detail{}

	// To find the Detail the parameter detail_id is used.
	if err := tx.Find(detail, c.Param("detail_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		c.Set("detail", detail)

		return c.Render(http.StatusOK, r.HTML("/details/show.plush.html"))
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(200, r.JSON(detail))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(200, r.XML(detail))
	}).Respond(c)
}

// Create adds a Detail to the DB. This function is mapped to the
// path POST /details
func (v DetailsResource) Create(c buffalo.Context) error {
	// Allocate an empty Detail
	detail := &models.Detail{}

	// Bind detail to the html form elements
	if err := c.Bind(detail); err != nil {
		return err
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(detail)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		return responder.Wants("html", func(c buffalo.Context) error {
			// Make the errors available inside the html template
			c.Set("errors", verrs)

			// Render again the new.html template that the user can
			// correct the input.
			c.Set("detail", detail)

			return c.Render(http.StatusUnprocessableEntity, r.HTML("/details/new.plush.html"))
		}).Wants("json", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
		}).Wants("xml", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
		}).Respond(c)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a success message
		c.Flash().Add("success", T.Translate(c, "detail.created.success"))

		// and redirect to the show page
		return c.Redirect(http.StatusSeeOther, "/details/%v", detail.ID)
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusCreated, r.JSON(detail))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusCreated, r.XML(detail))
	}).Respond(c)
}

// Update changes a Detail in the DB. This function is mapped to
// the path PUT /details/{detail_id}
func (v DetailsResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Detail
	detail := &models.Detail{}

	if err := tx.Find(detail, c.Param("detail_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	// Bind Detail to the html form elements
	if err := c.Bind(detail); err != nil {
		return err
	}

	verrs, err := tx.ValidateAndUpdate(detail)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		return responder.Wants("html", func(c buffalo.Context) error {
			// Make the errors available inside the html template
			c.Set("errors", verrs)

			// Render again the edit.html template that the user can
			// correct the input.
			c.Set("detail", detail)

			return c.Render(http.StatusUnprocessableEntity, r.HTML("/details/edit.plush.html"))
		}).Wants("json", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
		}).Wants("xml", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
		}).Respond(c)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a success message
		c.Flash().Add("success", T.Translate(c, "detail.updated.success"))

		// and redirect to the show page
		return c.Redirect(http.StatusSeeOther, "/details/%v", detail.ID)
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.JSON(detail))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.XML(detail))
	}).Respond(c)
}

// Destroy deletes a Detail from the DB. This function is mapped
// to the path DELETE /details/{detail_id}
func (v DetailsResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Detail
	detail := &models.Detail{}

	// To find the Detail the parameter detail_id is used.
	if err := tx.Find(detail, c.Param("detail_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	if err := tx.Destroy(detail); err != nil {
		return err
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a flash message
		c.Flash().Add("success", T.Translate(c, "detail.destroyed.success"))

		// Redirect to the index page
		return c.Redirect(http.StatusSeeOther, "/details")
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.JSON(detail))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.XML(detail))
	}).Respond(c)
}
